name: error-403
description: 403 Forbidden error page

trigger:
  - type: http
    path: /errors/403
    methods: [GET]
    public: true
    responses:
      html:
        enabled: true
      json:
        enabled: true

agents:
  - name: render-403
    operation: html
    config:
      templateEngine: liquid
      template: |
        <div class="error-page">
          <div class="error-content">
            <div class="error-code">403</div>
            <h1>Access Forbidden</h1>
            <p class="error-message">
              {% if message %}
              {{message}}
              {% else %}
              You don't have permission to access this resource. If you believe this is an error, please contact your administrator.
              {% endif %}
            </p>

            <div class="error-actions">
              <a href="/" class="btn-primary">Go Home</a>
              <a href="/login" class="btn-secondary">Log In</a>
            </div>

            {% if contactEmail %}
            <div class="contact-info">
              <p>Need help? Contact your administrator at <a href="mailto:{{contactEmail}}">{{contactEmail}}</a></p>
            </div>
            {% endif %}

            <p class="error-footer">Error Code: 403 | Access Denied</p>
          </div>
        </div>
      styles: |
        body {
          font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
          margin: 0;
          padding: 0;
          background: linear-gradient(135deg, #dc3545 0%, #c82333 100%);
          color: #333;
        }
        .error-page {
          min-height: 100vh;
          display: flex;
          align-items: center;
          justify-content: center;
          padding: 2rem;
        }
        .error-content {
          background: white;
          border-radius: 16px;
          padding: 3rem;
          max-width: 600px;
          width: 100%;
          text-align: center;
          box-shadow: 0 20px 60px rgba(0,0,0,0.3);
        }
        .error-code {
          font-size: 6rem;
          font-weight: 900;
          background: linear-gradient(135deg, #dc3545 0%, #c82333 100%);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
          background-clip: text;
          margin-bottom: 1rem;
          line-height: 1;
        }
        h1 {
          font-size: 2rem;
          margin: 0 0 1rem 0;
          color: #2d3748;
        }
        .error-message {
          font-size: 1.125rem;
          color: #718096;
          margin-bottom: 2rem;
          line-height: 1.6;
        }
        .error-actions {
          display: flex;
          gap: 1rem;
          justify-content: center;
          margin-bottom: 2rem;
          flex-wrap: wrap;
        }
        .btn-primary, .btn-secondary {
          padding: 0.875rem 2rem;
          border-radius: 8px;
          text-decoration: none;
          font-weight: 600;
          transition: all 0.3s;
          display: inline-block;
        }
        .btn-primary {
          background: linear-gradient(135deg, #dc3545 0%, #c82333 100%);
          color: white;
          border: none;
        }
        .btn-primary:hover {
          transform: translateY(-2px);
          box-shadow: 0 10px 20px rgba(220, 53, 69, 0.4);
        }
        .btn-secondary {
          background: #f7fafc;
          color: #dc3545;
          border: 2px solid #dc3545;
        }
        .btn-secondary:hover {
          background: #edf2f7;
        }
        .contact-info {
          margin: 2rem 0;
          padding: 1.5rem;
          background: #f7fafc;
          border-radius: 8px;
          color: #718096;
        }
        .contact-info a {
          color: #dc3545;
          text-decoration: none;
          font-weight: 600;
        }
        .contact-info a:hover {
          text-decoration: underline;
        }
        .error-footer {
          margin-top: 3rem;
          font-size: 0.875rem;
          color: #adb5bd;
        }
      seo:
        title: "403 - Forbidden"
        description: "You don't have permission to access this resource"
        robots: noindex, nofollow
      meta:
        - name: viewport
          content: width=device-width, initial-scale=1
        - http-equiv: status
          content: "403"
    input:
      message: $input.message
      contactEmail: $input.contactEmail

input:
  message: null
  contactEmail: null

output:
  html: ${render-403.output}
