/**
 * Conductor Worker - Auto-Discovery Example
 *
 * This is the RECOMMENDED approach for most projects.
 * Agents and ensembles are automatically discovered from your project directory.
 *
 * Features:
 * - Zero-config for 99% of users
 * - Auto-discovers agents from the agents/ directory
 * - Auto-discovers ensembles from the ensembles/ directory
 * - Provides unified /api/v1/execute endpoint
 * - Built-in authentication and logging
 */

import { createAutoDiscoveryAPI } from '@ensemble-edge/conductor/api'
import { ExecutionState, HITLState } from '@ensemble-edge/conductor/cloudflare'

// Import virtual modules generated by Vite plugins
import { agents } from 'virtual:conductor-agents'
import { ensembles } from 'virtual:conductor-ensembles'
import { docs } from 'virtual:conductor-docs'

/**
 * Create Conductor API with auto-discovery
 *
 * This automatically discovers and registers:
 * - All agents from the agents/ directory (YAML files)
 * - All ensembles from the ensembles/ directory (YAML files)
 * - All handlers from agent directories (index.ts files)
 */
export default createAutoDiscoveryAPI({
  // Enable auto-discovery (default: true)
  autoDiscover: true,

  // Pass discovered agents, ensembles, and docs from virtual modules
  agents,
  ensembles,
  docs,

  // Authentication configuration
  auth: {
    // API keys from environment (comma-separated)
    // Set via: wrangler secret put API_KEYS
    apiKeys: [],

    // Allow unauthenticated access (disable in production)
    allowAnonymous: true,
  },

  // Enable request logging
  logging: true,

  // CORS configuration
  cors: {
    origin: '*',
    allowMethods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
    allowHeaders: ['Content-Type', 'X-API-Key', 'Authorization'],
  },
})

/**
 * Export Durable Objects for stateful workflows
 * These are referenced in wrangler.toml
 */
export { ExecutionState, HITLState }

/**
 * Available Endpoints:
 *
 * POST /api/v1/execute
 * - Execute an agent or ensemble
 * - Body: { agent: "agent-name", input: {...} }
 * - OR: { ensemble: "ensemble-name", input: {...} }
 *
 * GET /api/v1/agents
 * - List all available agents
 *
 * GET /api/v1/ensembles (coming soon)
 * - List all available ensembles
 *
 * GET /health
 * - Health check endpoint
 *
 * POST /webhooks/:path
 * - Webhook triggers (configured per-ensemble)
 *
 * /mcp
 * - MCP server integration (configured per-ensemble)
 */
