/**
 * Type declarations for virtual modules generated by Vite plugins
 */

declare module 'virtual:conductor-docs' {
  export interface DocsDefinition {
    name: string
    content: string
  }

  export const docs: DocsDefinition[]
  export const docsMap: Map<string, DocsDefinition>
}

declare module 'virtual:conductor-agents' {
  export interface AgentDefinition {
    name: string
    config: string
    handler?: () => Promise<any>
  }

  export const agents: AgentDefinition[]
  export const agentsMap: Map<string, AgentDefinition>
}

declare module 'virtual:conductor-ensembles' {
  export interface EnsembleDefinition {
    name: string
    config: string
  }

  export const ensembles: EnsembleDefinition[]
  export const ensemblesMap: Map<string, EnsembleDefinition>
}

declare module 'virtual:conductor-scripts' {
  import type { AgentExecutionContext } from '@ensemble-edge/conductor'

  /**
   * Script handler function signature
   * Scripts receive the same context as agent handlers
   */
  export type ScriptHandler = (context: AgentExecutionContext) => Promise<any> | any

  export interface ScriptDefinition {
    name: string
    handler: ScriptHandler
  }

  export const scripts: ScriptDefinition[]

  /**
   * Map of script name to handler function
   * Used for resolving script:// URIs at runtime
   *
   * Example:
   *   scriptsMap.get('transforms/csv') // returns the handler function
   */
  export const scriptsMap: Map<string, ScriptHandler>
}
