name: ai-pipeline
description: |
  Multi-agent AI workflow using Workers AI.
  Demonstrates a 3-agent pipeline:
  1. Brainstormer - generates creative ideas
  2. Critic - evaluates and refines the ideas
  3. Summarizer - creates a polished final response

  This tests multi-step AI orchestration with schema output mapping.

flow:
  - agent: brainstorm
  - agent: critique
  - agent: summarize

trigger:
  - type: http
    path: /ai/think
    methods: [GET, POST]
    public: true

agents:
  # Step 1: Generate creative ideas
  - name: brainstorm
    operation: think
    config:
      provider: workers-ai
      model: "@cf/meta/llama-3.1-8b-instruct"
      temperature: 0.8
      maxTokens: 400
    schema:
      output:
        ideas: string
    prompt: |
      You are a creative brainstormer. Generate 3 interesting ideas or perspectives about the following topic.

      Topic: ${input.topic || "the future of edge computing"}

      Be creative and think outside the box. Format as a numbered list.

  # Step 2: Evaluate and refine
  - name: critique
    operation: think
    config:
      provider: workers-ai
      model: "@cf/meta/llama-3.1-8b-instruct"
      temperature: 0.5
      maxTokens: 400
    schema:
      output:
        analysis: string
    prompt: |
      You are a thoughtful critic. Review these ideas and identify the most promising one:

      ${brainstorm.output.ideas}

      Explain why you chose it and how it could be improved. Be constructive.

  # Step 3: Create polished summary
  - name: summarize
    operation: think
    config:
      provider: workers-ai
      model: "@cf/meta/llama-3.1-8b-instruct"
      temperature: 0.6
      maxTokens: 300
    schema:
      output:
        insight: string
    prompt: |
      Create a concise, polished summary combining the best idea with the critique's improvements.

      Original brainstorm: ${brainstorm.output.ideas}

      Critique and refinement: ${critique.output.analysis}

      Write a final, actionable insight in 2-3 sentences.

input:
  topic:
    type: string
    required: false
    description: The topic to brainstorm about (default is edge computing)

output:
  final_insight: ${summarize.output.insight}
  brainstorm_ideas: ${brainstorm.output.ideas}
  critique: ${critique.output.analysis}
