name: blog-post
description: Dynamic blog post page - demonstrates route parameters and database queries

trigger:
  - type: http
    path: /blog/:slug
    methods: [GET]
    public: true
    responses:
      html:
        enabled: true
      json:
        enabled: true

flow:
  - agent: fetch-blog-post
    input:
      slug: ${input.params.slug}
  - agent: fetch-related-posts
    input:
      excludeId: ${fetch-blog-post.output.post.id}

agents:
  # Render the blog post
  - name: render-post
    operation: html
    config:
      templateEngine: liquid
      template: |
        <div class="blog-post">
          {% if post %}
          <article>
            <header class="post-header">
              <h1>{{post.title}}</h1>
              <div class="post-meta">
                <span class="author">By {{post.author}}</span>
                <span class="date">{{post.published_at}}</span>
                <span class="reading-time">{{post.reading_time}} min read</span>
              </div>
            </header>

            {% if post.cover_image %}
            <img src="{{post.cover_image}}" alt="{{post.title}}" class="cover-image">
            {% endif %}

            <div class="post-content">
              {{post.content}}
            </div>

            <footer class="post-footer">
              <div class="tags">
                {% for tag in post.tags %}
                <a href="/blog/tag/{{tag}}" class="tag">{{tag}}</a>
                {% endfor %}
              </div>

              <div class="share-buttons">
                <button class="share-btn" hx-post="/api/share/twitter" hx-vals='{"url": "/blog/{{post.slug}}"}'>
                  Share on Twitter
                </button>
                <button class="share-btn" hx-post="/api/share/linkedin" hx-vals='{"url": "/blog/{{post.slug}}"}'>
                  Share on LinkedIn
                </button>
              </div>
            </footer>
          </article>

          {% if relatedPosts.size > 0 %}
          <aside class="related-posts">
            <h2>Related Posts</h2>
            <div class="related-grid">
              {% for related in relatedPosts %}
              <a href="/blog/{{related.slug}}" class="related-card">
                <h3>{{related.title}}</h3>
                <p>{{related.excerpt}}</p>
              </a>
              {% endfor %}
            </div>
          </aside>
          {% endif %}

          {% else %}
          <div class="not-found">
            <h1>Blog Post Not Found</h1>
            <p>The blog post you're looking for doesn't exist or has been removed.</p>
            <p>Requested slug: <code>{{slug}}</code></p>
            <a href="/blog" class="back-link">← Back to Blog</a>
          </div>
          {% endif %}
        </div>
      styles: |
        body {
          font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
          margin: 0;
          padding: 0;
          background: #f8f9fa;
        }
        .blog-post {
          max-width: 800px;
          margin: 0 auto;
          padding: 2rem;
        }
        article {
          background: white;
          padding: 3rem;
          border-radius: 12px;
          box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }
        .post-header {
          margin-bottom: 2rem;
          padding-bottom: 2rem;
          border-bottom: 2px solid #e9ecef;
        }
        .post-header h1 {
          font-size: 2.5rem;
          margin: 0 0 1rem 0;
          color: #212529;
          line-height: 1.2;
        }
        .post-meta {
          display: flex;
          gap: 1.5rem;
          color: #6c757d;
          font-size: 0.9rem;
        }
        .cover-image {
          width: 100%;
          height: auto;
          border-radius: 8px;
          margin-bottom: 2rem;
        }
        .post-content {
          font-size: 1.125rem;
          line-height: 1.8;
          color: #495057;
        }
        .post-content p {
          margin-bottom: 1.5rem;
        }
        .post-footer {
          margin-top: 3rem;
          padding-top: 2rem;
          border-top: 2px solid #e9ecef;
        }
        .tags {
          display: flex;
          gap: 0.5rem;
          flex-wrap: wrap;
          margin-bottom: 1.5rem;
        }
        .tag {
          padding: 0.5rem 1rem;
          background: #e7f3ff;
          color: #0066cc;
          text-decoration: none;
          border-radius: 20px;
          font-size: 0.875rem;
          transition: background 0.2s;
        }
        .tag:hover {
          background: #cce5ff;
        }
        .share-buttons {
          display: flex;
          gap: 1rem;
        }
        .share-btn {
          padding: 0.75rem 1.5rem;
          background: #667eea;
          color: white;
          border: none;
          border-radius: 8px;
          cursor: pointer;
          font-weight: 500;
          transition: background 0.2s;
        }
        .share-btn:hover {
          background: #5568d3;
        }
        .related-posts {
          margin-top: 3rem;
        }
        .related-posts h2 {
          font-size: 1.75rem;
          margin-bottom: 1.5rem;
          color: #212529;
        }
        .related-grid {
          display: grid;
          gap: 1.5rem;
        }
        .related-card {
          background: white;
          padding: 1.5rem;
          border-radius: 8px;
          text-decoration: none;
          color: inherit;
          box-shadow: 0 1px 4px rgba(0,0,0,0.1);
          transition: box-shadow 0.2s;
        }
        .related-card:hover {
          box-shadow: 0 4px 12px rgba(0,0,0,0.15);
        }
        .related-card h3 {
          margin: 0 0 0.5rem 0;
          color: #667eea;
        }
        .related-card p {
          margin: 0;
          color: #6c757d;
          font-size: 0.9rem;
        }
        .not-found {
          background: white;
          padding: 3rem;
          border-radius: 12px;
          box-shadow: 0 2px 8px rgba(0,0,0,0.1);
          text-align: center;
        }
        .not-found h1 {
          color: #e53e3e;
          margin-bottom: 1rem;
        }
        .not-found code {
          background: #f7fafc;
          padding: 0.25rem 0.5rem;
          border-radius: 4px;
          font-family: monospace;
        }
        .back-link {
          display: inline-block;
          margin-top: 2rem;
          padding: 0.75rem 1.5rem;
          background: #667eea;
          color: white;
          text-decoration: none;
          border-radius: 8px;
          transition: background 0.2s;
        }
        .back-link:hover {
          background: #5568d3;
        }
      seo:
        title: "{{post.title}}"
        description: "{{post.excerpt}}"
        canonical: "/blog/{{post.slug}}"
      meta:
        - name: viewport
          content: width=device-width, initial-scale=1
        - property: og:type
          content: article
      scripts:
        - src: https://unpkg.com/htmx.org@1.9.10
    input:
      post: ${fetch-blog-post.output.post}
      relatedPosts: ${fetch-related-posts.output.rows}
      slug: ${input.params.slug}

output:
  post: ${fetch-blog-post.output.post}
  found: ${fetch-blog-post.output.found}
  relatedPosts: ${fetch-related-posts.output.rows}
  requestedSlug: ${input.params.slug}
