name: homepage
description: Homepage example - demonstrates server-side rendering with dynamic content

trigger:
  - type: http
    path: /
    methods: [GET]
    public: true
    # HTTP cache headers - homepage can be cached briefly
    httpCache:
      public: true
      maxAge: 60  # 1 minute - balance freshness vs performance
      staleWhileRevalidate: 300  # Serve stale for 5 mins while revalidating
      vary: [Accept]  # Vary by Accept header (HTML vs JSON)
    responses:
      html:
        enabled: true
      json:
        enabled: true

flow:
  - agent: fetch-features
  - agent: fetch-latest-posts

agents:
  # Render homepage
  - name: render-homepage
    operation: html
    config:
      templateEngine: liquid
      template: |
        <div class="homepage">
          <div class="hero">
            <div class="hero-content">
              <h1>{{siteName}}</h1>
              <p class="tagline">{{tagline}}</p>
              <div class="cta-buttons">
                <a href="/dashboard" class="btn-primary">Get Started</a>
                <a href="/login" class="btn-secondary">Sign In</a>
              </div>
            </div>
          </div>

          <div class="features-section">
            <div class="container">
              <h2>Features</h2>
              <div class="features-grid">
                {% for feature in features %}
                <div class="feature-card">
                  <div class="feature-icon">{{feature.icon}}</div>
                  <h3>{{feature.title}}</h3>
                  <p>{{feature.description}}</p>
                </div>
                {% endfor %}
              </div>
            </div>
          </div>

          {% if latestPosts.size > 0 %}
          <div class="blog-section">
            <div class="container">
              <h2>Latest from the Blog</h2>
              <div class="blog-grid">
                {% for post in latestPosts %}
                <a href="/blog/{{post.slug}}" class="blog-card">
                  <h3>{{post.title}}</h3>
                  <p>{{post.excerpt}}</p>
                  <span class="read-more">Read more →</span>
                </a>
                {% endfor %}
              </div>
              <div class="blog-cta">
                <a href="/blog" class="btn-secondary">View All Posts</a>
              </div>
            </div>
          </div>
          {% endif %}

          <div class="cta-section">
            <div class="container">
              <h2>Ready to get started?</h2>
              <p>Join thousands of teams building with Conductor</p>
              <a href="/signup" class="btn-primary btn-large">Sign Up Free</a>
            </div>
          </div>

          <footer class="footer">
            <div class="container">
              <div class="footer-content">
                <div class="footer-column">
                  <h4>Product</h4>
                  <a href="/features">Features</a>
                  <a href="/pricing">Pricing</a>
                  <a href="/docs">Documentation</a>
                </div>
                <div class="footer-column">
                  <h4>Company</h4>
                  <a href="/about">About</a>
                  <a href="/blog">Blog</a>
                  <a href="/careers">Careers</a>
                </div>
                <div class="footer-column">
                  <h4>Support</h4>
                  <a href="/support">Contact</a>
                  <a href="/status">Status</a>
                  <a href="/community">Community</a>
                </div>
              </div>
              <div class="footer-bottom">
                <p>&copy; 2024 {{siteName}}. All rights reserved.</p>
              </div>
            </div>
          </footer>
        </div>
      styles: |
        * {
          box-sizing: border-box;
        }
        body {
          font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
          margin: 0;
          padding: 0;
          color: #212529;
        }
        .container {
          max-width: 1200px;
          margin: 0 auto;
          padding: 0 2rem;
        }
        .hero {
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          color: white;
          padding: 6rem 2rem;
          text-align: center;
        }
        .hero-content {
          max-width: 800px;
          margin: 0 auto;
        }
        .hero h1 {
          font-size: 3.5rem;
          margin: 0 0 1rem 0;
          font-weight: 700;
        }
        .tagline {
          font-size: 1.5rem;
          margin: 0 0 2rem 0;
          opacity: 0.95;
        }
        .cta-buttons {
          display: flex;
          gap: 1rem;
          justify-content: center;
          flex-wrap: wrap;
        }
        .btn-primary, .btn-secondary {
          padding: 1rem 2rem;
          border-radius: 8px;
          text-decoration: none;
          font-weight: 600;
          font-size: 1rem;
          transition: all 0.3s;
          display: inline-block;
        }
        .btn-primary {
          background: white;
          color: #667eea;
        }
        .btn-primary:hover {
          transform: translateY(-2px);
          box-shadow: 0 10px 20px rgba(0,0,0,0.2);
        }
        .btn-secondary {
          background: rgba(255,255,255,0.2);
          color: white;
          border: 2px solid white;
        }
        .btn-secondary:hover {
          background: rgba(255,255,255,0.3);
        }
        .btn-large {
          padding: 1.25rem 3rem;
          font-size: 1.125rem;
        }
        .features-section {
          padding: 6rem 0;
          background: white;
        }
        .features-section h2 {
          text-align: center;
          font-size: 2.5rem;
          margin: 0 0 3rem 0;
        }
        .features-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
          gap: 2rem;
        }
        .feature-card {
          text-align: center;
          padding: 2rem;
        }
        .feature-icon {
          font-size: 3rem;
          margin-bottom: 1rem;
        }
        .feature-card h3 {
          font-size: 1.25rem;
          margin: 0 0 1rem 0;
        }
        .feature-card p {
          color: #6c757d;
          line-height: 1.6;
          margin: 0;
        }
        .blog-section {
          padding: 6rem 0;
          background: #f8f9fa;
        }
        .blog-section h2 {
          text-align: center;
          font-size: 2.5rem;
          margin: 0 0 3rem 0;
        }
        .blog-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
          gap: 2rem;
          margin-bottom: 3rem;
        }
        .blog-card {
          background: white;
          padding: 2rem;
          border-radius: 12px;
          text-decoration: none;
          color: inherit;
          box-shadow: 0 2px 8px rgba(0,0,0,0.1);
          transition: all 0.3s;
        }
        .blog-card:hover {
          transform: translateY(-4px);
          box-shadow: 0 8px 16px rgba(0,0,0,0.15);
        }
        .blog-card h3 {
          color: #667eea;
          margin: 0 0 1rem 0;
        }
        .blog-card p {
          color: #6c757d;
          margin: 0 0 1rem 0;
          line-height: 1.6;
        }
        .read-more {
          color: #667eea;
          font-weight: 600;
        }
        .blog-cta {
          text-align: center;
        }
        .cta-section {
          padding: 6rem 0;
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          color: white;
          text-align: center;
        }
        .cta-section h2 {
          font-size: 2.5rem;
          margin: 0 0 1rem 0;
        }
        .cta-section p {
          font-size: 1.25rem;
          margin: 0 0 2rem 0;
          opacity: 0.95;
        }
        .footer {
          padding: 4rem 0 2rem 0;
          background: #2d3748;
          color: white;
        }
        .footer-content {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
          gap: 2rem;
          margin-bottom: 3rem;
        }
        .footer-column h4 {
          margin: 0 0 1rem 0;
          font-size: 1.125rem;
        }
        .footer-column a {
          display: block;
          color: rgba(255,255,255,0.8);
          text-decoration: none;
          margin-bottom: 0.75rem;
          transition: color 0.2s;
        }
        .footer-column a:hover {
          color: white;
        }
        .footer-bottom {
          text-align: center;
          padding-top: 2rem;
          border-top: 1px solid rgba(255,255,255,0.1);
        }
        .footer-bottom p {
          margin: 0;
          color: rgba(255,255,255,0.6);
        }
      seo:
        title: "{{siteName}} - {{tagline}}"
        description: "{{tagline}}"
        canonical: /
      meta:
        - name: viewport
          content: width=device-width, initial-scale=1
        - property: og:type
          content: website
    input:
      siteName: ${input.siteName}
      tagline: ${input.tagline}
      features: ${fetch-features.output.rows}
      latestPosts: ${fetch-latest-posts.output.rows}

input:
  siteName: Conductor
  tagline: Edge-native orchestration for AI agents

output:
  siteName: ${input.siteName}
  tagline: ${input.tagline}
  features: ${fetch-features.output.rows}
  latestPosts: ${fetch-latest-posts.output.rows}
