name: middleware-demo
description: Demonstrates HTTP middleware usage

trigger:
  - type: http
    path: /api/demo
    methods: [GET, POST]
    public: true
    middleware:
      - logger
      - timing
      - secure-headers
      - etag
    responses:
      json:
        enabled: true

flow:
  - agent: process-middleware-request

output:
  result: ${process-middleware-request.output}
