name: smart-500
description: AI-powered 500 error page that logs errors, notifies team, and provides helpful troubleshooting

trigger:
  - type: http
    path: /errors/smart-500
    methods: [GET, POST]
    public: true
    responses:
      html:
        enabled: true
      json:
        enabled: true

agents:
  # Log the error with full context
  - name: log-error
    operation: code
    config:
      script: scripts/examples/http/log-error
    input:
      error: $input.error
      stack: $input.stack
      requestPath: $input.path
      requestId: $input.requestId

  # Send notification to team (if configured)
  - name: notify-team
    operation: email
    config:
      to: $input.alertEmail
      subject: "🚨 Production Error: {{errorId}}"
      body: |
        A 500 error occurred in production:

        Error ID: {{errorId}}
        Path: {{requestPath}}
        Message: {{errorMessage}}
        Time: {{timestamp}}

        View details: {{dashboardUrl}}/errors/{{errorId}}
    input:
      errorId: $log-error.errorId
      requestPath: $input.path
      errorMessage: $input.error
      timestamp: $input.timestamp
      alertEmail: $input.config.alertEmail
      dashboardUrl: $input.config.dashboardUrl
    when: $input.config.notifyOnError

  # Use AI to suggest troubleshooting steps
  - name: suggest-troubleshooting
    operation: think
    config:
      model: gpt-4-mini
      systemPrompt: |
        You are a helpful technical support assistant. Based on the error details,
        suggest 3-5 troubleshooting steps the user can try, or explain what might have gone wrong.
        Be concise and practical. Format as a JSON array of strings.
      temperature: 0.7
    input:
      userPrompt: |
        Error occurred at path: {{requestPath}}
        Error message: {{errorMessage}}

        Suggest 3-5 troubleshooting steps or explanations.
        Return as JSON array: ["step 1", "step 2", ...]
      requestPath: $input.path
      errorMessage: $input.error
    when: $input.config.aiSuggestions

  # Render the smart 500 page
  - name: render-500
    operation: html
    config:
      templateEngine: liquid
      template: |
        <div class="error-page smart-500">
          <div class="error-content">
            <div class="error-code">500</div>
            <h1>Something Went Wrong</h1>
            <p class="error-message">
              We're sorry, but something unexpected happened. Our team has been notified and is working on it.
            </p>

            <div class="error-id-box">
              <strong>Error ID:</strong> <code>{{errorId}}</code>
              <p class="error-id-help">Reference this ID when contacting support for faster assistance.</p>
            </div>

            {% if troubleshootingSteps %}
            <div class="troubleshooting">
              <h2>What you can try:</h2>
              <ul>
                {% for step in troubleshootingSteps %}
                <li>{{step}}</li>
                {% endfor %}
              </ul>
            </div>
            {% endif %}

            <div class="error-actions">
              <a href="/" class="btn-primary">Go Home</a>
              <button onclick="location.reload()" class="btn-secondary">Try Again</button>
              <a href="/support?error={{errorId}}" class="btn-secondary">Contact Support</a>
            </div>

            {% if dev %}
            <div class="error-details">
              <h2>Error Details (Dev Mode)</h2>
              <div class="error-stack">
                <strong>Message:</strong>
                <pre>{{errorMessage}}</pre>
                {% if errorStack %}
                <strong>Stack Trace:</strong>
                <pre>{{errorStack}}</pre>
                {% endif %}
              </div>
            </div>
            {% endif %}

            <div class="status-section">
              <p>Check our <a href="/status" target="_blank">status page</a> for updates on system health.</p>
            </div>
          </div>
        </div>
      styles: |
        body {
          font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
          margin: 0;
          padding: 0;
          background: linear-gradient(135deg, #fc5c7d 0%, #6a82fb 100%);
          color: #333;
        }
        .error-page {
          min-height: 100vh;
          display: flex;
          align-items: center;
          justify-content: center;
          padding: 2rem;
        }
        .error-content {
          background: white;
          border-radius: 16px;
          padding: 3rem;
          max-width: 800px;
          width: 100%;
          text-align: center;
          box-shadow: 0 20px 60px rgba(0,0,0,0.3);
        }
        .error-code {
          font-size: 6rem;
          font-weight: 900;
          background: linear-gradient(135deg, #fc5c7d 0%, #6a82fb 100%);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
          background-clip: text;
          margin-bottom: 1rem;
          line-height: 1;
        }
        h1 {
          font-size: 2rem;
          margin: 0 0 1rem 0;
          color: #2d3748;
        }
        .error-message {
          font-size: 1.125rem;
          color: #718096;
          margin-bottom: 2rem;
          line-height: 1.6;
        }
        .error-id-box {
          background: #f7fafc;
          border: 2px solid #e2e8f0;
          border-radius: 8px;
          padding: 1.5rem;
          margin: 2rem 0;
        }
        .error-id-box code {
          font-family: 'Monaco', 'Courier New', monospace;
          font-size: 1rem;
          color: #fc5c7d;
          background: white;
          padding: 0.5rem 1rem;
          border-radius: 4px;
          display: inline-block;
          margin: 0.5rem 0;
        }
        .error-id-help {
          font-size: 0.875rem;
          color: #718096;
          margin: 0.75rem 0 0 0;
        }
        .troubleshooting {
          text-align: left;
          margin: 2rem 0;
          background: #f7fafc;
          padding: 1.5rem;
          border-radius: 8px;
        }
        .troubleshooting h2 {
          margin-top: 0;
          color: #2d3748;
          font-size: 1.25rem;
        }
        .troubleshooting ul {
          margin: 1rem 0 0 0;
          padding-left: 1.5rem;
        }
        .troubleshooting li {
          margin-bottom: 0.75rem;
          color: #4a5568;
          line-height: 1.6;
        }
        .error-actions {
          display: flex;
          gap: 1rem;
          justify-content: center;
          margin: 2rem 0;
          flex-wrap: wrap;
        }
        .btn-primary, .btn-secondary {
          padding: 0.875rem 2rem;
          border-radius: 8px;
          text-decoration: none;
          font-weight: 600;
          transition: all 0.3s;
          display: inline-block;
          cursor: pointer;
          border: none;
          background: none;
        }
        .btn-primary {
          background: linear-gradient(135deg, #fc5c7d 0%, #6a82fb 100%);
          color: white;
        }
        .btn-primary:hover {
          transform: translateY(-2px);
          box-shadow: 0 10px 20px rgba(252, 92, 125, 0.4);
        }
        .btn-secondary {
          background: #f7fafc;
          color: #fc5c7d;
          border: 2px solid #fc5c7d;
        }
        .btn-secondary:hover {
          background: #edf2f7;
        }
        .error-details {
          text-align: left;
          margin-top: 2rem;
          padding: 1.5rem;
          background: #2d3748;
          border-radius: 8px;
          color: white;
        }
        .error-details h2 {
          margin-top: 0;
          font-size: 1.125rem;
          color: #fc5c7d;
        }
        .error-stack {
          font-size: 0.875rem;
        }
        .error-stack pre {
          background: #1a202c;
          padding: 1rem;
          border-radius: 4px;
          overflow-x: auto;
          white-space: pre-wrap;
          word-wrap: break-word;
          margin: 0.5rem 0 1rem 0;
        }
        .status-section {
          margin-top: 2rem;
          padding-top: 1.5rem;
          border-top: 1px solid #e2e8f0;
          color: #718096;
        }
        .status-section a {
          color: #fc5c7d;
          text-decoration: none;
          font-weight: 600;
        }
        .status-section a:hover {
          text-decoration: underline;
        }
      seo:
        title: "500 - Internal Server Error"
        description: "An error occurred while processing your request"
        robots: noindex, nofollow
      meta:
        - name: viewport
          content: width=device-width, initial-scale=1
        - http-equiv: status
          content: "500"
    input:
      errorId: $log-error.errorId
      errorMessage: $input.error
      errorStack: $input.stack
      troubleshootingSteps: $suggest-troubleshooting.steps
      dev: $input.dev

input:
  error: null
  stack: null
  path: null
  requestId: null
  timestamp: null
  dev: false
  config:
    notifyOnError: false
    aiSuggestions: true
    alertEmail: alerts@example.com
    dashboardUrl: https://dashboard.example.com

output:
  html: ${render-500.output}
