name: csv-export
description: |
  CSV data export example using the format system.
  Demonstrates automatic Content-Type (text/csv) via format: csv
  with built-in array-to-CSV serialization.

trigger:
  - type: http
    path: /export/users.csv
    methods: [GET]
    public: true

# For real applications, you would fetch data from a database:
# agents:
#   - name: fetch-users
#     operation: data
#     config:
#       database: d1
#       query: SELECT id, name, email, created_at FROM users ORDER BY created_at DESC

agents:
  - name: mock-users
    operation: transform
    config:
      expression: |
        [
          { "id": 1, "name": "Alice Johnson", "email": "alice@example.com", "created_at": "2024-01-15" },
          { "id": 2, "name": "Bob Smith", "email": "bob@example.com", "created_at": "2024-01-16" },
          { "id": 3, "name": "Carol Williams", "email": "carol@example.com", "created_at": "2024-01-17" },
          { "id": 4, "name": "David Brown", "email": "david@example.com", "created_at": "2024-01-18" }
        ]

flow:
  - agent: mock-users

# The format: csv option will:
# 1. Set Content-Type: text/csv
# 2. Auto-serialize array of objects to CSV (headers from object keys)
# 3. Extract the 'users' field from body since extract is specified
output:
  status: 200
  headers:
    Content-Disposition: attachment; filename="users.csv"
  format:
    type: csv
    extract: users
  body:
    users: ${mock-users.output}
