name: ics-calendar
description: |
  iCalendar (.ics) export example using the format system.
  Demonstrates automatic Content-Type (text/calendar) via format: ics
  for calendar event downloads.

trigger:
  - type: http
    path: /calendar/event.ics
    methods: [GET]
    public: true

agents:
  - name: generate-ics
    operation: html
    config:
      templateEngine: liquid
      template: |
        BEGIN:VCALENDAR
        VERSION:2.0
        PRODID:-//Conductor//Event Generator//EN
        CALSCALE:GREGORIAN
        METHOD:PUBLISH
        BEGIN:VEVENT
        UID:{{uid}}
        DTSTAMP:{{dtstamp}}
        DTSTART:{{dtstart}}
        DTEND:{{dtend}}
        SUMMARY:{{summary}}
        DESCRIPTION:{{description}}
        LOCATION:{{location}}
        {% if url %}URL:{{url}}{% endif %}
        {% if organizer %}ORGANIZER;CN={{organizer.name}}:mailto:{{organizer.email}}{% endif %}
        STATUS:CONFIRMED
        SEQUENCE:0
        END:VEVENT
        END:VCALENDAR

flow:
  - agent: generate-ics
    input:
      uid: ${input.uid}
      dtstamp: ${input.dtstamp}
      dtstart: ${input.dtstart}
      dtend: ${input.dtend}
      summary: ${input.summary}
      description: ${input.description}
      location: ${input.location}
      url: ${input.url}
      organizer: ${input.organizer}

input:
  uid:
    type: string
    default: "event-123@example.com"
  dtstamp:
    type: string
    default: "20240115T120000Z"
  dtstart:
    type: string
    default: "20240201T140000Z"
  dtend:
    type: string
    default: "20240201T160000Z"
  summary:
    type: string
    default: "Team Meeting"
  description:
    type: string
    default: "Weekly team sync to discuss project progress"
  location:
    type: string
    default: "Conference Room A"
  url:
    type: string
    required: false
  organizer:
    type: object
    required: false
    default:
      name: "John Doe"
      email: "john@example.com"

output:
  status: 200
  headers:
    Content-Disposition: attachment; filename="event.ics"
  format: ics
  body:
    calendar: ${generate-ics.output.html}
