name: docs-generate
version: 1.0.0
description: |
  Generate documentation artifacts (OpenAPI spec, static pages).
  Can be triggered at build time, via CLI, or on a schedule.

trigger:
  # Build-time trigger - runs during `conductor build` or deploy
  - type: build
    enabled: true
    output: ./dist/docs

  # CLI trigger - run via `conductor run docs-generate`
  - type: cli
    command: docs-generate
    description: Generate OpenAPI documentation
    options:
      - name: format
        type: string
        default: yaml
        description: Output format (json or yaml)
      - name: output
        type: string
        description: Output directory path

  # Scheduled trigger - regenerate docs periodically (disabled by default)
  - type: cron
    cron: "0 0 * * *"
    enabled: false
    metadata:
      description: Daily docs regeneration at midnight

flow:
  - name: generate
    agent: docs
    input:
      action: generate-openapi
      format: "${trigger.options.format || 'yaml'}"
    config:
      title: API Documentation
      description: Auto-generated API documentation

output:
  success: "${flow.generate.output.success}"
  spec: "${flow.generate.output.spec}"
  specYaml: "${flow.generate.output.specYaml}"
  specJson: "${flow.generate.output.specJson}"
  message: "${trigger.type == 'build' ? 'OpenAPI spec generated for build' : trigger.type == 'cron' ? 'Scheduled docs regeneration complete' : 'Documentation generated successfully'}"
