# Debug Slow Endpoint
#
# Responds after a configurable delay.
# Useful for testing timeout handling and loading states.
#
# Usage: GET /debug/slow?ms=2000

name: debug-slow
version: 1.0.0
description: Endpoint with configurable delay for timeout testing

trigger:
  - type: http
    path: /debug/slow
    methods: [GET]
    public: true

flow:
  - agent: delay
    input:
      ms: ${ trigger.query.ms ?? 1000 }
      passthrough:
        requested: ${ trigger.query.ms ?? 1000 }

output:
  status: 200
  body:
    delayed: ${ delay.output.delayed }
    requestedMs: ${ delay.output.passthrough.requested }
    actualMs: ${ delay.output.actualDelayMs }
    note: "Delay may vary on free tier (scheduler.wait unavailable)"
