name: contact-form
description: Simple contact form with validation and email notification

trigger:
  - type: http
    path: /contact
    methods: [GET, POST]
    public: true

agents:
  # Render contact form
  - name: render-form
    operation: form
    config:
      title: Contact Us
      description: We'd love to hear from you. Send us a message and we'll respond as soon as possible.
      fields:
        - name: name
          operation: text
          label: Your Name
          placeholder: John Doe
          validation:
            required: true
            minLength:
              value: 2
              message: Name must be at least 2 characters
            maxLength:
              value: 100
              message: Name must be at most 100 characters

        - name: email
          operation: email
          label: Email Address
          placeholder: john@example.com
          autocomplete: email
          validation:
            required: true
            email: true

        - name: subject
          operation: select
          label: Subject
          options:
            - label: General Inquiry
              value: general
            - label: Technical Support
              value: support
            - label: Sales Question
              value: sales
            - label: Partnership Opportunity
              value: partnership
          validation:
            required: true

        - name: message
          operation: textarea
          label: Message
          placeholder: Tell us how we can help...
          rows: 6
          validation:
            required: true
            minLength:
              value: 10
              message: Message must be at least 10 characters
            maxLength:
              value: 1000
              message: Message must be at most 1000 characters

        - name: subscribe
          operation: checkbox
          label: Subscribe to our newsletter

      submitText: Send Message
      honeypot: _website
      rateLimit:
        max: 5
        window: 3600 # 1 hour
      csrf:
        enabled: true
        secret: ${CSRF_SECRET}
      style:
        includeDefaultStyles: true
        classes:
          form: contact-form
          button: btn btn-primary

  # Send notification email when form is submitted
  - name: send-notification
    operation: email
    config:
      from:
        email: noreply@example.com
        name: Contact Form
      to:
        - email: support@example.com
          name: Support Team
      subject: "New Contact Form Submission: {{subject}}"
      template: |
        <h2>New Contact Form Submission</h2>

        <p><strong>From:</strong> {{name}} ({{email}})</p>
        <p><strong>Subject:</strong> {{subject}}</p>

        <h3>Message:</h3>
        <p>{{message}}</p>

        {{#if subscribe}}
        <p><em>Note: This person has opted in to receive newsletter updates.</em></p>
        {{/if}}

        <hr>
        <p style="color: #666; font-size: 12px;">
          Submitted at: {{timestamp}}
        </p>
    input:
      name: ${render-form.data.name}
      email: ${render-form.data.email}
      subject: ${render-form.data.subject}
      message: ${render-form.data.message}
      subscribe: ${render-form.data.subscribe}
      timestamp: ${now}

  # Send confirmation email to user
  - name: send-confirmation
    operation: email
    config:
      from:
        email: noreply@example.com
        name: Example Company
      to:
        - email: ${render-form.data.email}
          name: ${render-form.data.name}
      subject: "We received your message"
      template: |
        <h2>Thank You for Contacting Us!</h2>

        <p>Hi {{name}},</p>

        <p>We've received your message and will get back to you as soon as possible,
        usually within 24-48 hours.</p>

        <h3>Your Message:</h3>
        <blockquote style="border-left: 3px solid #ccc; padding-left: 15px; color: #666;">
          {{message}}
        </blockquote>

        <p>If you have any urgent concerns, please call us at (555) 123-4567.</p>

        <p>Best regards,<br>
        The Example Company Team</p>
    input:
      name: ${render-form.data.name}
      message: ${render-form.data.message}
    condition: ${render-form.valid}

output:
  formHtml: ${render-form.html}
  valid: ${render-form.valid}
  errors: ${render-form.errors}
  emailSent: ${send-notification.success}
  confirmationSent: ${send-confirmation.success}
