name: data-export-report
description: Export user activity data to CSV/JSON/Excel with filtering and streaming support

trigger:
  - type: http
    path: /reports/export
    methods: [GET]
    public: true

agents:
  # Query user activity data with filters
  - name: query-data
    operation: storage
    config:
      backend: kv
      action: list
      binding: CACHE
      prefix: 'user:activity:'
      limit: 5000

  # Export to CSV format
  - name: export-csv
    operation: code
    config:
      script: scripts/examples/data/export-to-csv
    input:
      data: ${query-data.keys}

  # Export to JSON format
  - name: export-json
    operation: code
    config:
      script: scripts/examples/data/export-to-json
    input:
      data: ${query-data.keys}
      pretty: ${input.prettyJson}

  # Export to Excel format (simulated)
  - name: export-excel
    operation: code
    config:
      script: scripts/examples/data/export-to-excel
    input:
      data: ${query-data.keys}

  # Generate HTML report with export links
  - name: generate-report
    operation: html
    config:
      template: |
        <!DOCTYPE html>
        <html>
        <head>
          <title>Data Export Report</title>
          <style>
            body {
              font-family: system-ui, -apple-system, sans-serif;
              max-width: 1200px;
              margin: 40px auto;
              padding: 20px;
            }
            h1 { color: #2D1B69; }
            .export-card {
              background: white;
              border: 1px solid #e2e8f0;
              border-radius: 8px;
              padding: 24px;
              margin: 20px 0;
            }
            .export-card h3 {
              margin-top: 0;
              color: #1a202c;
            }
            .stats {
              display: grid;
              grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
              gap: 16px;
              margin: 24px 0;
            }
            .stat-card {
              background: #f7fafc;
              padding: 16px;
              border-radius: 6px;
            }
            .stat-value {
              font-size: 32px;
              font-weight: bold;
              color: #2D1B69;
            }
            .stat-label {
              color: #718096;
              font-size: 14px;
            }
            .download-btn {
              display: inline-block;
              padding: 10px 20px;
              background: #2D1B69;
              color: white;
              text-decoration: none;
              border-radius: 6px;
              margin-right: 10px;
              margin-top: 10px;
            }
            .download-btn:hover {
              background: #1A0F4A;
            }
          </style>
        </head>
        <body>
          <h1>📊 Data Export Report</h1>

          <div class="stats">
            <div class="stat-card">
              <div class="stat-value">{{query-data.count}}</div>
              <div class="stat-label">Total Records</div>
            </div>
            <div class="stat-card">
              <div class="stat-value">{{export-csv.size}}</div>
              <div class="stat-label">CSV Size (bytes)</div>
            </div>
            <div class="stat-card">
              <div class="stat-value">{{#if export-csv.streaming}}Yes{{else}}No{{/if}}</div>
              <div class="stat-label">Streaming Mode</div>
            </div>
          </div>

          <div class="export-card">
            <h3>📄 CSV Export</h3>
            <p>Comma-separated values format, compatible with Excel and Google Sheets.</p>
            <a href="/export/csv" class="download-btn">Download CSV</a>
            <div style="margin-top: 12px; color: #718096; font-size: 14px;">
              <strong>Format:</strong> text/csv<br>
              <strong>Records:</strong> {{export-csv.count}}<br>
              <strong>Streaming:</strong> {{#if export-csv.streaming}}Enabled{{else}}Disabled{{/if}}
            </div>
          </div>

          <div class="export-card">
            <h3>📋 JSON Export</h3>
            <p>JavaScript Object Notation format, ideal for API consumption and data processing.</p>
            <a href="/export/json" class="download-btn">Download JSON</a>
            <div style="margin-top: 12px; color: #718096; font-size: 14px;">
              <strong>Format:</strong> application/json<br>
              <strong>Records:</strong> {{export-json.count}}<br>
              <strong>Size:</strong> {{export-json.size}} bytes
            </div>
          </div>

          <div class="export-card">
            <h3>📊 Excel Export</h3>
            <p>Microsoft Excel format (.xlsx), ready for advanced analysis and pivot tables.</p>
            <a href="/export/excel" class="download-btn">Download Excel</a>
            <div style="margin-top: 12px; color: #718096; font-size: 14px;">
              <strong>Format:</strong> application/vnd.openxmlformats-officedocument.spreadsheetml.sheet<br>
              <strong>Records:</strong> {{export-excel.count}}<br>
              <strong>Sheet Name:</strong> User Activity
            </div>
          </div>

          <h2>Sample Data</h2>
          <pre style="background: #f7fafc; padding: 16px; border-radius: 6px; overflow-x: auto;">{{export-json.data}}</pre>
        </body>
        </html>
    input:
      query-data: ${query-data}
      export-csv: ${export-csv}
      export-json: ${export-json}
      export-excel: ${export-excel}

output:
  html: ${generate-report.html}
  query: ${query-data}
  exports:
    csv: ${export-csv}
    json: ${export-json}
    excel: ${export-excel}
