name: invoice-extractor
description: Extract structured invoice data from documents using schema components

flow:
  - agent: extract-invoice

# Trigger via webhook for easy integration
trigger:
  - type: webhook
    path: /webhooks/extract/invoice  # Recommended: /webhooks/* prefix
    methods: [POST]
    public: false
    auth:
      type: bearer
      secret: ${env.API_TOKEN}

agents:
  - name: extract-invoice
    operation: think
    config:
      provider: anthropic
      model: claude-sonnet-4
      temperature: 0.1  # Low temperature for accurate extraction
      maxTokens: 4000
      prompt: |
        Extract invoice information from the following document.
        Return the data in the structured format specified.

        Document:
        ${input.document}
      # Reference the invoice schema component
      schema: schemas/invoice@v1

input:
  document:
    type: string
    required: true
    description: The invoice document text or image URL to extract data from

output:
  invoice: ${extract-invoice.output}
  invoice_number: ${extract-invoice.output.invoice_number}
  total: ${extract-invoice.output.total}
  vendor_name: ${extract-invoice.output.vendor.name}
