name: pdf-email
description: |
  Generate a PDF and email it as an attachment.
  Demonstrates:
  - PDF generation from HTML template
  - Email with PDF attachments
  - Binary data handling for attachments
  - Custom PDF styling and metadata

trigger:
  - type: http
    path: /api/pdf-email
    methods: [POST]
    public: true

flow:
  # Step 1: Generate PDF from HTML
  - agent: generate-pdf
    operation: pdf
    config:
      template: invoice  # Or use inline HTML with 'html' property
      storage:
        enabled: true
        binding: STORAGE
      browser:
        binding: BROWSER
    input:
      html: |
        <!DOCTYPE html>
        <html>
        <head>
          <style>
            body {
              font-family: Arial, sans-serif;
              padding: 40px;
            }
            .header {
              text-align: center;
              margin-bottom: 40px;
            }
            .invoice-details {
              margin: 20px 0;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin: 20px 0;
            }
            th, td {
              border: 1px solid #ddd;
              padding: 12px;
              text-align: left;
            }
            th {
              background-color: #4CAF50;
              color: white;
            }
            .total {
              font-size: 1.2em;
              font-weight: bold;
              text-align: right;
              margin-top: 20px;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>{{title}}</h1>
            <p>Invoice #{{invoiceNumber}}</p>
            <p>Date: {{date}}</p>
          </div>

          <div class="invoice-details">
            <p><strong>Bill To:</strong></p>
            <p>{{customer.name}}</p>
            <p>{{customer.email}}</p>
          </div>

          <table>
            <thead>
              <tr>
                <th>Description</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Total</th>
              </tr>
            </thead>
            <tbody>
              {{#each items}}
              <tr>
                <td>{{this.description}}</td>
                <td>{{this.quantity}}</td>
                <td>${{this.price}}</td>
                <td>${{this.total}}</td>
              </tr>
              {{/each}}
            </tbody>
          </table>

          <div class="total">
            Total: ${{totalAmount}}
          </div>
        </body>
        </html>
      data:
        title: ${input.title}
        invoiceNumber: ${input.invoiceNumber}
        date: ${now}
        customer: ${input.customer}
        items: ${input.items}
        totalAmount: ${input.totalAmount}
      pdfOptions:
        format: "A4"
        printBackground: true
        margin:
          top: "20mm"
          bottom: "20mm"
          left: "15mm"
          right: "15mm"
      filename: ${input.filename}
    output: pdfResult

  # Step 2: Prepare PDF attachment
  - agent: prepare-pdf-attachment
    operation: code
    config:
      script: scripts/examples/data/prepare-pdf-attachment
    input:
      pdfResult: ${generate-pdf}
      filename: ${input.filename}
    output: attachment

  # Step 3: Send email with PDF attachment
  - agent: send-email
    operation: email
    config:
      provider:
        operation: resend
        apiKey: ${env.RESEND_API_KEY}
        from: "invoices@example.com"
    input:
      to: ${input.recipient}
      subject: ${input.emailSubject}
      html: |
        <h2>{{greeting}}</h2>
        <p>{{message}}</p>
        <p>Please find the attached {{documentType}}.</p>
        <ul>
          <li><strong>Document:</strong> {{filename}}</li>
          <li><strong>Size:</strong> {{fileSize}} KB</li>
        </ul>
        <p>Thank you for your business!</p>
      data:
        greeting: ${input.greeting}
        message: ${input.emailMessage}
        documentType: ${input.documentType}
        filename: ${prepare-pdf-attachment.filename}
        fileSize: ${Math.round(generate-pdf.size / 1024)}
      attachments:
        - filename: ${prepare-pdf-attachment.filename}
          content: ${prepare-pdf-attachment.content}
          contentType: ${prepare-pdf-attachment.contentType}
          encoding: ${prepare-pdf-attachment.encoding}

output:
  emailSent: ${send-email}
  pdfUrl: ${generate-pdf.url}
  pdfSize: ${generate-pdf.size}

# Input schema
schema:
  input:
    title: string
    invoiceNumber: string
    customer:
      name: string
      email: string
    items: array
    totalAmount: number
    recipient: string
    emailSubject: string
    greeting: string?
    emailMessage: string?
    documentType: string?
    filename: string?

# Example usage:
#   POST /execute/pdf-email
#   {
#     "title": "Invoice",
#     "invoiceNumber": "INV-2024-001",
#     "customer": {
#       "name": "John Doe",
#       "email": "john@example.com"
#     },
#     "items": [
#       {
#         "description": "Web Development Services",
#         "quantity": 40,
#         "price": 150,
#         "total": 6000
#       },
#       {
#         "description": "Hosting (Annual)",
#         "quantity": 1,
#         "price": 500,
#         "total": 500
#       }
#     ],
#     "totalAmount": 6500,
#     "recipient": "john@example.com",
#     "emailSubject": "Invoice #INV-2024-001",
#     "greeting": "Hi John,",
#     "emailMessage": "Thank you for your business! Here's your invoice for this month.",
#     "documentType": "invoice",
#     "filename": "invoice-2024-001.pdf"
#   }
