name: pdf-download
description: |
  Generate and download a PDF report directly.
  Demonstrates:
  - PDF generation from data
  - Download headers (Content-Disposition: attachment)
  - Binary response handling
  - Custom filename for downloads
  - Conditional outputs with custom headers

trigger:
  - type: http
    path: /reports/pdf/:reportId
    methods: [GET]
    public: true

flow:
  # Step 1: Fetch data for the report
  - agent: fetch-report-data
    operation: data
    config:
      backend: d1
      binding: DB
      operation: query
      sql: |
        SELECT * FROM reports
        WHERE id = ?
      params:
        - ${input.reportId}
    output: reportData

  # Step 2: Generate PDF from the data
  - agent: generate-report-pdf
    operation: pdf
    config:
      browser:
        binding: BROWSER
      storage:
        enabled: true  # Store in R2 for future downloads
        binding: STORAGE
    input:
      html: |
        <!DOCTYPE html>
        <html>
        <head>
          <style>
            @page {
              margin: 20mm;
              size: A4 portrait;
            }
            body {
              font-family: 'Helvetica', Arial, sans-serif;
              color: #333;
              line-height: 1.6;
            }
            .header {
              border-bottom: 3px solid #4CAF50;
              padding-bottom: 20px;
              margin-bottom: 30px;
            }
            .header h1 {
              margin: 0;
              color: #4CAF50;
            }
            .meta {
              color: #666;
              font-size: 0.9em;
              margin-top: 10px;
            }
            .section {
              margin: 30px 0;
            }
            .section h2 {
              color: #4CAF50;
              border-bottom: 2px solid #ddd;
              padding-bottom: 10px;
            }
            .data-table {
              width: 100%;
              border-collapse: collapse;
              margin: 20px 0;
            }
            .data-table th,
            .data-table td {
              border: 1px solid #ddd;
              padding: 12px;
              text-align: left;
            }
            .data-table th {
              background-color: #4CAF50;
              color: white;
              font-weight: bold;
            }
            .data-table tr:nth-child(even) {
              background-color: #f9f9f9;
            }
            .footer {
              margin-top: 50px;
              text-align: center;
              color: #666;
              font-size: 0.85em;
              border-top: 1px solid #ddd;
              padding-top: 20px;
            }
            .summary-box {
              background: #f0f8ff;
              border-left: 4px solid #4CAF50;
              padding: 15px;
              margin: 20px 0;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>{{title}}</h1>
            <div class="meta">
              <strong>Report ID:</strong> {{reportId}} |
              <strong>Generated:</strong> {{generatedAt}} |
              <strong>Period:</strong> {{period}}
            </div>
          </div>

          <div class="section">
            <h2>Summary</h2>
            <div class="summary-box">
              <p>{{summary}}</p>
            </div>
          </div>

          <div class="section">
            <h2>Detailed Data</h2>
            <table class="data-table">
              <thead>
                <tr>
                  {{#each columns}}
                  <th>{{this}}</th>
                  {{/each}}
                </tr>
              </thead>
              <tbody>
                {{#each rows}}
                <tr>
                  {{#each this}}
                  <td>{{this}}</td>
                  {{/each}}
                </tr>
                {{/each}}
              </tbody>
            </table>
          </div>

          <div class="footer">
            <p>This report was automatically generated by Conductor.</p>
            <p>© {{year}} Your Company Name. All rights reserved.</p>
          </div>
        </body>
        </html>
      data:
        title: ${input.title}
        reportId: ${input.reportId}
        generatedAt: ${now}
        period: ${input.period}
        summary: ${fetch-report-data.summary}
        columns: ${input.columns}
        rows: ${fetch-report-data.items}
        year: ${new Date().getFullYear()}
      pdfOptions:
        format: "A4"
        printBackground: true
        margin:
          top: "20mm"
          bottom: "20mm"
          left: "15mm"
          right: "15mm"
      filename: ${`report-${input.reportId}-${Date.now()}.pdf`}
      disposition: "attachment"  # Forces download instead of inline display

output:
  # Success: Return PDF with download headers
  - when: ${generate-report-pdf.success}
    status: 200
    headers:
      Content-Type: application/pdf
      Content-Disposition: ${generate-report-pdf.contentDisposition}
    rawBody: ${generate-report-pdf.pdf}

  # Not found - report doesn't exist
  - when: ${fetch-report-data.output.error === 'not_found'}
    status: 404
    body:
      error: "Report not found"
      reportId: ${input.reportId}

  # Error fallback
  - status: 500
    body:
      error: "PDF generation failed"
      message: ${generate-report-pdf.output.error}

# Input schema
schema:
  input:
    reportId: string
    title: string
    period: string
    columns: array

# Example usage:
#   GET /execute/pdf-download?reportId=RPT-2024-001&title=Sales%20Report&period=Q1%202024&columns=["Month","Sales","Profit"]
#
# The response will have these headers:
#   Content-Type: application/pdf
#   Content-Disposition: attachment; filename="report-RPT-2024-001-1234567890.pdf"
#
# This will trigger a browser download with the specified filename
