name: user-registration
description: Multi-step user registration form with validation, CAPTCHA, and welcome email

trigger:
  - type: http
    path: /register
    methods: [GET, POST]
    public: true

agents:
  # Multi-step registration form
  - name: registration-form
    operation: form
    config:
      title: Create Your Account
      description: Join thousands of users already enjoying our platform
      steps:
        # Step 1: Account Information
        - id: account
          title: Account Information
          description: Choose your username and password
          fields:
            - name: username
              operation: text
              label: Username
              placeholder: johndoe
              autocomplete: username
              help: Choose a unique username (3-20 characters, letters and numbers only)
              validation:
                required: true
                minLength:
                  value: 3
                  message: Username must be at least 3 characters
                maxLength:
                  value: 20
                  message: Username must be at most 20 characters
                pattern:
                  regex: ^[a-zA-Z0-9]+$
                  message: Username can only contain letters and numbers

            - name: email
              operation: email
              label: Email Address
              placeholder: john@example.com
              autocomplete: email
              validation:
                required: true
                email: true

            - name: password
              operation: password
              label: Password
              autocomplete: new-password
              help: Must be at least 8 characters with at least one number
              validation:
                required: true
                minLength:
                  value: 8
                  message: Password must be at least 8 characters
                pattern:
                  regex: ^(?=.*[0-9]).+$
                  message: Password must contain at least one number

            - name: confirmPassword
              operation: password
              label: Confirm Password
              autocomplete: new-password
              validation:
                required: true
                matches:
                  field: password
                  message: Passwords must match

        # Step 2: Personal Information
        - id: personal
          title: Personal Information
          description: Tell us a bit about yourself
          fields:
            - name: firstName
              operation: text
              label: First Name
              placeholder: John
              autocomplete: given-name
              validation:
                required: true
                minLength: 2

            - name: lastName
              operation: text
              label: Last Name
              placeholder: Doe
              autocomplete: family-name
              validation:
                required: true
                minLength: 2

            - name: dateOfBirth
              operation: date
              label: Date of Birth
              autocomplete: bday
              max: ${TODAY}
              validation:
                required: true

            - name: country
              operation: select
              label: Country
              autocomplete: country
              options:
                - label: United States
                  value: US
                - label: Canada
                  value: CA
                - label: United Kingdom
                  value: GB
                - label: Australia
                  value: AU
                - label: Germany
                  value: DE
                - label: France
                  value: FR
                - label: Other
                  value: OTHER
              validation:
                required: true

        # Step 3: Preferences
        - id: preferences
          title: Preferences
          description: Customize your experience
          fields:
            - name: notifications
              operation: checkbox
              label: Email notifications
              default: true
              help: Receive updates about your account activity

            - name: newsletter
              operation: checkbox
              label: Subscribe to newsletter
              help: Get weekly tips and product updates

            - name: interests
              operation: select
              label: Interests
              multiple: true
              options:
                - Technology
                - Business
                - Design
                - Marketing
                - Development
                - Data Science
              help: Select all that apply (optional)

            - name: howDidYouHear
              operation: radio
              label: How did you hear about us?
              options:
                - label: Search Engine
                  value: search
                - label: Social Media
                  value: social
                - label: Friend Referral
                  value: referral
                - label: Blog/Article
                  value: blog
                - label: Advertisement
                  value: ad
                - label: Other
                  value: other
              validation:
                required: true

      submitText: Create Account
      honeypot: _url
      captcha:
        operation: turnstile
        siteKey: ${TURNSTILE_SITE_KEY}
        secretKey: ${TURNSTILE_SECRET_KEY}
        theme: auto
      csrf:
        enabled: true
        secret: ${CSRF_SECRET}
      rateLimit:
        max: 3
        window: 900 # 15 minutes
      style:
        includeDefaultStyles: true
        classes:
          form: registration-form
          button: btn btn-primary btn-lg

  # Validate username availability (simulated)
  - name: check-username
    operation: code
    config:
      script: scripts/examples/auth/check-username
    input:
      username: ${registration-form.data.username}
    condition: ${registration-form.valid}

  # Create user account (simulated)
  - name: create-account
    operation: code
    config:
      script: scripts/examples/auth/create-account
    input:
      username: ${registration-form.data.username}
      email: ${registration-form.data.email}
      password: ${registration-form.data.password}
      firstName: ${registration-form.data.firstName}
      lastName: ${registration-form.data.lastName}
      dateOfBirth: ${registration-form.data.dateOfBirth}
      country: ${registration-form.data.country}
    condition: ${registration-form.valid && check-username.available}

  # Send welcome email
  - name: send-welcome-email
    operation: email
    config:
      from:
        email: welcome@example.com
        name: Example Company
      to:
        - email: ${registration-form.data.email}
          name: "${registration-form.data.firstName} ${registration-form.data.lastName}"
      subject: "Welcome to Example Company, {{firstName}}!"
      template: |
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h1 style="color: #2D1B69;">Welcome to Example Company!</h1>

          <p>Hi {{firstName}},</p>

          <p>Thank you for creating an account with us! We're excited to have you on board.</p>

          <div style="background: #F5F1E8; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h3 style="margin-top: 0;">Your Account Details</h3>
            <p><strong>Username:</strong> {{username}}<br>
            <strong>Email:</strong> {{email}}</p>
          </div>

          <h3>Next Steps:</h3>
          <ol>
            <li>Verify your email address by clicking the button below</li>
            <li>Complete your profile</li>
            <li>Explore our features and tools</li>
          </ol>

          <div style="text-align: center; margin: 30px 0;">
            <a href="https://example.com/verify?token={{verificationToken}}"
               style="background: #2D1B69; color: white; padding: 12px 30px;
                      text-decoration: none; border-radius: 5px; display: inline-block;">
              Verify Email Address
            </a>
          </div>

          <p>If you didn't create this account, please ignore this email or contact our
          support team.</p>

          <p>Best regards,<br>
          The Example Company Team</p>

          <hr style="border: none; border-top: 1px solid #ddd; margin: 30px 0;">

          <p style="color: #666; font-size: 12px;">
            This email was sent to {{email}}. If you have questions, reply to this email
            or visit our <a href="https://example.com/help">help center</a>.
          </p>
        </div>
    input:
      firstName: ${registration-form.data.firstName}
      username: ${registration-form.data.username}
      email: ${registration-form.data.email}
      verificationToken: ${create-account.verificationToken}
    condition: ${create-account.created}

  # Send admin notification
  - name: notify-admin
    operation: email
    config:
      from:
        email: system@example.com
        name: System Notifications
      to:
        - email: admin@example.com
          name: Admin Team
      subject: "New User Registration: {{username}}"
      template: |
        <h3>New User Registered</h3>

        <p><strong>Username:</strong> {{username}}<br>
        <strong>Email:</strong> {{email}}<br>
        <strong>Name:</strong> {{firstName}} {{lastName}}<br>
        <strong>Country:</strong> {{country}}<br>
        <strong>User ID:</strong> {{userId}}</p>

        <p><strong>Preferences:</strong></p>
        <ul>
          <li>Email notifications: {{notifications}}</li>
          <li>Newsletter: {{newsletter}}</li>
          <li>How they heard about us: {{howDidYouHear}}</li>
        </ul>
    input:
      username: ${registration-form.data.username}
      email: ${registration-form.data.email}
      firstName: ${registration-form.data.firstName}
      lastName: ${registration-form.data.lastName}
      country: ${registration-form.data.country}
      userId: ${create-account.userId}
      notifications: ${registration-form.data.notifications}
      newsletter: ${registration-form.data.newsletter}
      howDidYouHear: ${registration-form.data.howDidYouHear}
    condition: ${create-account.created}

output:
  formHtml: ${registration-form.html}
  currentStep: ${registration-form.currentStep}
  nextStep: ${registration-form.nextStep}
  isLastStep: ${registration-form.isLastStep}
  valid: ${registration-form.valid}
  errors: ${registration-form.errors}
  accountCreated: ${create-account.created}
  userId: ${create-account.userId}
  welcomeEmailSent: ${send-welcome-email.success}
